//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIM.VSNDK_Package {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RIM.VSNDK_Package.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to specify the Author name.
        /// </summary>
        internal static string AuthorMissing {
            get {
                return ResourceManager.GetString("AuthorMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is important that you back up your signing keys. If you should lose your signing keys, or forget your password, you will be required to re-register with BlackBerry. After re-registering, new versions of your applications will appear as new applications, and will not have access to shared data from previous versions. Exporting your signing keys will also allow you to import them to multiple computers allow you to sign from any of them..
        /// </summary>
        internal static string BackupRestoreInfo {
            get {
                return ResourceManager.GetString("BackupRestoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create tool window..
        /// </summary>
        internal static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to specify a confirm password.
        /// </summary>
        internal static string CSJConfirmPasswordMissing {
            get {
                return ResourceManager.GetString("CSJConfirmPasswordMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to specify a BlackBerry ID token password and it must be at least 6 characters long.
        /// </summary>
        internal static string CSJPasswordMissing {
            get {
                return ResourceManager.GetString("CSJPasswordMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to provide the Pin.
        /// </summary>
        internal static string CSJPinMissing {
            get {
                return ResourceManager.GetString("CSJPinMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bar-descriptor Designer.
        /// </summary>
        internal static string ErrorMessageBoxTitle {
            get {
                return ResourceManager.GetString("ErrorMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        internal static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vstemplate file you are attempting to load is missing TemplateData.
        /// </summary>
        internal static string InvalidVsTemplateData {
            get {
                return ResourceManager.GetString("InvalidVsTemplateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check if the Natvie SDK is installed..
        /// </summary>
        internal static string NativSDKNotInstalled {
            get {
                return ResourceManager.GetString("NativSDKNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Passwords do not match..
        /// </summary>
        internal static string PasswordNotmatch {
            get {
                return ResourceManager.GetString("PasswordNotmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDK CSJ file is required!.
        /// </summary>
        internal static string RDKCSJFileMissing {
            get {
                return ResourceManager.GetString("RDKCSJFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reformat.
        /// </summary>
        internal static string ReformatBuffer {
            get {
                return ResourceManager.GetString("ReformatBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the &quot;Author Name&quot; and the password that was used to create the BlackBerry ID token..
        /// </summary>
        internal static string RegistrationInfo {
            get {
                return ResourceManager.GetString("RegistrationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize XML file with view.
        /// </summary>
        internal static string SynchronizeBuffer {
            get {
                return ResourceManager.GetString("SynchronizeBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing.
        /// </summary>
        internal static string ToolWindowTitle {
            get {
                return ResourceManager.GetString("ToolWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to unregister and remove the BlackBerry ID Token file?.
        /// </summary>
        internal static string UnRegistrationInfo {
            get {
                return ResourceManager.GetString("UnRegistrationInfo", resourceCulture);
            }
        }
    }
}
