//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace BlackBerry.BarDescriptor.Model {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qnx.com/schemas/application/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("qnx", Namespace="http://www.qnx.com/schemas/application/1.0", IsNullable=false)]
    public partial class QnxRootType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private LocalizedStringType nameField;
        
        private string versionNumberField;
        
        private string platformVersionField;
        
        private string buildIdField;
        
        private LocalizedStringType descriptionField;
        
        private LocalizedStringType copyrightField;
        
        private string authorField;
        
        private string authorIdField;
        
        private string categoryField;
        
        private WindowType initialWindowField;
        
        private AssetType[] assetField;
        
        private ConfigurationType[] configurationField;
        
        private EntryPointType[] entryPointField;
        
        private ImageType iconField;
        
        private ImageType splashScreensField;
        
        private string splashscreenField;
        
        private PermissionType[] actionField;
        
        private PermissionType[] permissionField;
        
        private EnvironmentVarType[] envField;
        
        private InvokeTargetType[] invoketargetField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        public LocalizedStringType name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        public string versionNumber {
            get {
                return this.versionNumberField;
            }
            set {
                this.versionNumberField = value;
                this.RaisePropertyChanged("versionNumber");
            }
        }
        
        /// <remarks/>
        public string platformVersion {
            get {
                return this.platformVersionField;
            }
            set {
                this.platformVersionField = value;
                this.RaisePropertyChanged("platformVersion");
            }
        }
        
        /// <remarks/>
        public string buildId {
            get {
                return this.buildIdField;
            }
            set {
                this.buildIdField = value;
                this.RaisePropertyChanged("buildId");
            }
        }
        
        /// <remarks/>
        public LocalizedStringType description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        public LocalizedStringType copyright {
            get {
                return this.copyrightField;
            }
            set {
                this.copyrightField = value;
                this.RaisePropertyChanged("copyright");
            }
        }
        
        /// <remarks/>
        public string author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
                this.RaisePropertyChanged("author");
            }
        }
        
        /// <remarks/>
        public string authorId {
            get {
                return this.authorIdField;
            }
            set {
                this.authorIdField = value;
                this.RaisePropertyChanged("authorId");
            }
        }
        
        /// <remarks/>
        public string category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("category");
            }
        }
        
        /// <remarks/>
        public WindowType initialWindow {
            get {
                return this.initialWindowField;
            }
            set {
                this.initialWindowField = value;
                this.RaisePropertyChanged("initialWindow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("asset")]
        public AssetType[] asset {
            get {
                return this.assetField;
            }
            set {
                this.assetField = value;
                this.RaisePropertyChanged("asset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("configuration")]
        public ConfigurationType[] configuration {
            get {
                return this.configurationField;
            }
            set {
                this.configurationField = value;
                this.RaisePropertyChanged("configuration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entryPoint")]
        public EntryPointType[] entryPoint {
            get {
                return this.entryPointField;
            }
            set {
                this.entryPointField = value;
                this.RaisePropertyChanged("entryPoint");
            }
        }
        
        /// <remarks/>
        public ImageType icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
                this.RaisePropertyChanged("icon");
            }
        }
        
        /// <remarks/>
        public ImageType splashScreens {
            get {
                return this.splashScreensField;
            }
            set {
                this.splashScreensField = value;
                this.RaisePropertyChanged("splashScreens");
            }
        }
        
        /// <remarks/>
        public string splashscreen {
            get {
                return this.splashscreenField;
            }
            set {
                this.splashscreenField = value;
                this.RaisePropertyChanged("splashscreen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("action", IsNullable=true)]
        public PermissionType[] action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("permission")]
        public PermissionType[] permission {
            get {
                return this.permissionField;
            }
            set {
                this.permissionField = value;
                this.RaisePropertyChanged("permission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("env")]
        public EnvironmentVarType[] env {
            get {
                return this.envField;
            }
            set {
                this.envField = value;
                this.RaisePropertyChanged("env");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("invoke-target")]
        public InvokeTargetType[] invoketarget {
            get {
                return this.invoketargetField;
            }
            set {
                this.invoketargetField = value;
                this.RaisePropertyChanged("invoketarget");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qnx.com/schemas/application/1.0")]
    public partial class LocalizedStringType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] textField;
        
        private string[] textField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("text")]
        public string[] text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField1;
            }
            set {
                this.textField1 = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qnx.com/schemas/application/1.0")]
    public partial class InvokeTargetFilterType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string actionField;
        
        private string mimetypeField;
        
        private EnvironmentVarType propertyField;
        
        /// <remarks/>
        public string action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mime-type")]
        public string mimetype {
            get {
                return this.mimetypeField;
            }
            set {
                this.mimetypeField = value;
                this.RaisePropertyChanged("mimetype");
            }
        }
        
        /// <remarks/>
        public EnvironmentVarType property {
            get {
                return this.propertyField;
            }
            set {
                this.propertyField = value;
                this.RaisePropertyChanged("property");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qnx.com/schemas/application/1.0")]
    public partial class EnvironmentVarType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string varField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string var {
            get {
                return this.varField;
            }
            set {
                this.varField = value;
                this.RaisePropertyChanged("var");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qnx.com/schemas/application/1.0")]
    public partial class InvokeTargetType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string invoketargettypeField;
        
        private string invoketargetnameField;
        
        private string entrypointidField;
        
        private ImageType iconField;
        
        private InvokeTargetFilterType filterField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("invoke-target-type")]
        public string invoketargettype {
            get {
                return this.invoketargettypeField;
            }
            set {
                this.invoketargettypeField = value;
                this.RaisePropertyChanged("invoketargettype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("invoke-target-name")]
        public string invoketargetname {
            get {
                return this.invoketargetnameField;
            }
            set {
                this.invoketargetnameField = value;
                this.RaisePropertyChanged("invoketargetname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entry-point-id")]
        public string entrypointid {
            get {
                return this.entrypointidField;
            }
            set {
                this.entrypointidField = value;
                this.RaisePropertyChanged("entrypointid");
            }
        }
        
        /// <remarks/>
        public ImageType icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
                this.RaisePropertyChanged("icon");
            }
        }
        
        /// <remarks/>
        public InvokeTargetFilterType filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
                this.RaisePropertyChanged("filter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qnx.com/schemas/application/1.0")]
    public partial class ImageType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] imageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("image")]
        public string[] image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
                this.RaisePropertyChanged("image");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qnx.com/schemas/application/1.0")]
    public partial class PermissionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string systemField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string system {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
                this.RaisePropertyChanged("system");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qnx.com/schemas/application/1.0")]
    public partial class EntryPointType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string entryPointTypeField;
        
        private PermissionType[] permissionField;
        
        private string idField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        public string entryPointType {
            get {
                return this.entryPointTypeField;
            }
            set {
                this.entryPointTypeField = value;
                this.RaisePropertyChanged("entryPointType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("permission")]
        public PermissionType[] permission {
            get {
                return this.permissionField;
            }
            set {
                this.permissionField = value;
                this.RaisePropertyChanged("permission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qnx.com/schemas/application/1.0")]
    public partial class ConfigurationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] platformArchitectureField;
        
        private string[] entryPointTypeField;
        
        private AssetType[] assetField;
        
        private string idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("platformArchitecture")]
        public string[] platformArchitecture {
            get {
                return this.platformArchitectureField;
            }
            set {
                this.platformArchitectureField = value;
                this.RaisePropertyChanged("platformArchitecture");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entryPointType")]
        public string[] entryPointType {
            get {
                return this.entryPointTypeField;
            }
            set {
                this.entryPointTypeField = value;
                this.RaisePropertyChanged("entryPointType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("asset")]
        public AssetType[] asset {
            get {
                return this.assetField;
            }
            set {
                this.assetField = value;
                this.RaisePropertyChanged("asset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qnx.com/schemas/application/1.0")]
    public partial class AssetType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AssetTypeInclude[] includeField;
        
        private string[] textField;
        
        private string publicField;
        
        private string pathField;
        
        private string entryField;
        
        private string typeField;
        
        private string entryPointIdField;
        
        private string destField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("include")]
        public AssetTypeInclude[] include {
            get {
                return this.includeField;
            }
            set {
                this.includeField = value;
                this.RaisePropertyChanged("include");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @public {
            get {
                return this.publicField;
            }
            set {
                this.publicField = value;
                this.RaisePropertyChanged("public");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
                this.RaisePropertyChanged("path");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string entry {
            get {
                return this.entryField;
            }
            set {
                this.entryField = value;
                this.RaisePropertyChanged("entry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string entryPointId {
            get {
                return this.entryPointIdField;
            }
            set {
                this.entryPointIdField = value;
                this.RaisePropertyChanged("entryPointId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dest {
            get {
                return this.destField;
            }
            set {
                this.destField = value;
                this.RaisePropertyChanged("dest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qnx.com/schemas/application/1.0")]
    public partial class AssetTypeInclude : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qnx.com/schemas/application/1.0")]
    public partial class WindowType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aspectRatioField;
        
        private string autoOrientsField;
        
        private string systemChromeField;
        
        private string transparentField;
        
        /// <remarks/>
        public string aspectRatio {
            get {
                return this.aspectRatioField;
            }
            set {
                this.aspectRatioField = value;
                this.RaisePropertyChanged("aspectRatio");
            }
        }
        
        /// <remarks/>
        public string autoOrients {
            get {
                return this.autoOrientsField;
            }
            set {
                this.autoOrientsField = value;
                this.RaisePropertyChanged("autoOrients");
            }
        }
        
        /// <remarks/>
        public string systemChrome {
            get {
                return this.systemChromeField;
            }
            set {
                this.systemChromeField = value;
                this.RaisePropertyChanged("systemChrome");
            }
        }
        
        /// <remarks/>
        public string transparent {
            get {
                return this.transparentField;
            }
            set {
                this.transparentField = value;
                this.RaisePropertyChanged("transparent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
